### ISSUE TITLE
Don't use String.Casing it breaks in Elixir 1.6

### ISSUE THREAD

**Issue by olafura** [blackode/elixir-tips#5]
For what I can see it's an internal function in Elixir. `String.downcase` and `String.upcase`works you are describing ;)

**Comment by blackode** [comment]
Updated the things you as mentioned. Check at  #6  [file-changes](https://github.com/blackode/elixir-tips/pull/6/files)
Thank You :bouquet:

**Comment by olafura** [comment]
@blackode Thanks for the quick update ;)
